name: ingestion

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10 #install the python needed
          run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python ingest.py
